(function(){
 'use strict';
 var key='kic.cart.items', form=document.getElementById('kic-checkout-form'), feedback=document.getElementById('kic-checkout-feedback'), summary=document.getElementById('kic-summary'), total=document.getElementById('kic-summary-total'), zone=document.getElementById('kic-zone');
 function items(){try{return JSON.parse(localStorage.getItem(key))||[]}catch(e){return[]}}
 function render(){var list=items(),sum=0;summary.innerHTML=list.length?list.map(function(i){var cents=Math.round(Number(i.price||0)*100);sum+=cents;return '<div class="kic-summary-item"><span>'+i.name+'<small> · '+(i.format||'Format standard')+'</small></span><strong>'+(cents?KICAPI.money(cents):'Sur devis')+'</strong></div>'}).join(''):'<p>Votre panier est vide. <a href="produits.html">Voir les produits</a></p>';total.textContent=KICAPI.money(sum)}
 async function zones(){try{var rows=await KICAPI.zones();zone.innerHTML=rows.map(function(z){return '<option value="'+z.id+'">'+z.name+' — '+KICAPI.money(z.fee)+'</option>'}).join('')}catch(e){zone.innerHTML='<option value="">Zones indisponibles</option>'}}
 form.addEventListener('submit',async function(e){e.preventDefault();feedback.textContent='';var list=items();if(!list.length){feedback.textContent='Votre panier est vide.';return}var submit=form.querySelector('[type=submit]');submit.disabled=true;submit.textContent='Envoi en cours…';try{for(var i=0;i<list.length;i++){if(!list[i].variantId)throw new Error('Actualisez le catalogue puis ajoutez de nouveau « '+list[i].name+' ».');await KICAPI.add(list[i].variantId,1)}var raw=Object.fromEntries(new FormData(form));raw.cartToken=KICAPI.token();if(raw.deliveryMethod==='PICKUP')delete raw.deliveryZoneId;else raw.deliveryZoneId=Number(raw.deliveryZoneId);var order=await KICAPI.checkout(raw);sessionStorage.setItem('kic.last.order',JSON.stringify(order));localStorage.removeItem(key);location.href='confirmation.html?order='+encodeURIComponent(order.orderNumber)}catch(err){feedback.textContent=err.message||'La commande n’a pas pu être envoyée.';submit.disabled=false;submit.textContent='Envoyer ma commande →'}});
 render();zones();
})();
