(function(){
 'use strict';
 var key='kic.cart.items', form=document.getElementById('kic-checkout-form'), feedback=document.getElementById('kic-checkout-feedback'), summary=document.getElementById('kic-summary'), total=document.getElementById('kic-summary-total'), zone=document.getElementById('kic-zone'), zoneField=document.getElementById('kic-zone-field'), deliveryMethod=document.getElementById('kic-delivery-method'), deliveryZones=[];
 function items(){try{return JSON.parse(localStorage.getItem(key))||[]}catch(e){return[]}}
 function render(){var list=items(),sum=0;summary.innerHTML=list.length?list.map(function(i){var cents=Math.round(Number(i.price||0)*100);sum+=cents;return '<div class="kic-summary-item"><span>'+i.name+'<small> · '+(i.format||'Format standard')+'</small></span><strong>'+(cents?KICAPI.money(cents):'Sur devis')+'</strong></div>'}).join(''):'<p>Votre panier est vide. <a href="produits.html">Voir les produits</a></p>';total.textContent=KICAPI.money(sum)}
 function renderZones(){var pickup=deliveryMethod.value==='PICKUP';if(pickup){zone.innerHTML='<option value="">Non applicable — retrait à Nice</option>';return}var rows=deliveryZones.filter(function(z){return !/retrait|pickup/i.test(z.name)});zone.innerHTML=rows.map(function(z){return '<option value="'+z.id+'">'+z.name+' — '+KICAPI.money(z.fee)+'</option>'}).join('')||'<option value="">Zones indisponibles</option>';var france=rows.find(function(z){return /france métropolitaine/i.test(z.name)});if(france)zone.value=String(france.id)}
 async function zones(){try{deliveryZones=await KICAPI.zones();renderZones()}catch(e){zone.innerHTML='<option value="">Zones indisponibles</option>'}}
 function syncDelivery(){var pickup=deliveryMethod.value==='PICKUP';renderZones();zone.disabled=pickup;zone.required=!pickup;zoneField.classList.toggle('is-disabled',pickup)}
 deliveryMethod.addEventListener('change',syncDelivery);syncDelivery();
 form.addEventListener('submit',async function(e){e.preventDefault();feedback.textContent='';var list=items();if(!list.length){feedback.textContent='Votre panier est vide.';return}var submit=form.querySelector('[type=submit]'),original=submit.innerHTML;submit.disabled=true;submit.innerHTML='<span class="kic-payment-spinner" aria-hidden="true"></span><span><strong>Préparation du paiement…</strong><small>Connexion sécurisée à Stripe</small></span>';try{for(var i=0;i<list.length;i++){if(!list[i].variantId)throw new Error('Actualisez le catalogue puis ajoutez de nouveau « '+list[i].name+' ».');await KICAPI.add(list[i].variantId,1)}var raw=Object.fromEntries(new FormData(form));raw.cartToken=KICAPI.token();if(raw.deliveryMethod==='PICKUP')delete raw.deliveryZoneId;else raw.deliveryZoneId=Number(raw.deliveryZoneId);var order=await KICAPI.checkout(raw);sessionStorage.setItem('kic.last.order',JSON.stringify(order));var payment=await KICAPI.stripeCheckout(order.orderNumber,order.accessToken);location.assign(payment.checkoutUrl)}catch(err){feedback.textContent=err.message||'Le paiement n’a pas pu être préparé.';submit.disabled=false;submit.innerHTML=original}});
 if(new URLSearchParams(location.search).get('payment')==='cancelled')feedback.textContent='Paiement annulé. Votre carte n’a pas été débitée. Vous pouvez recommencer.';
 render();zones();
})();
