<?php
declare(strict_types=1);

function audit_admin(array $admin,int $status=200): void { if(in_array($_SERVER['REQUEST_METHOD'],['POST','PUT','PATCH','DELETE'],true))db()->prepare('INSERT INTO audit_logs(actor,method,path,status) VALUES(?,?,?,?)')->execute([$admin['email'],$_SERVER['REQUEST_METHOD'],request_path(),$status]); }
function admin_orders(): never { $where=['1=1'];$bind=[];if($s=$_GET['status']??null){$where[]='o.status=?';$bind[]=$s;}if($q=trim((string)($_GET['q']??''))){$where[]='(o.order_number LIKE ? OR o.recipient_name LIKE ? OR o.contact_email LIKE ?)';$bind=array_merge($bind,["%$q%","%$q%","%$q%"]);}$sql=implode(' AND ',$where);$count=db()->prepare("SELECT COUNT(*) FROM orders o WHERE $sql");$count->execute($bind);$total=(int)$count->fetchColumn();$page=max(0,(int)($_GET['page']??0));$size=min(100,max(1,(int)($_GET['size']??20)));$query=db()->prepare("SELECT o.*,z.name zone_name,z.estimated_days_min,z.estimated_days_max FROM orders o LEFT JOIN delivery_zones z ON z.id=o.delivery_zone_id WHERE $sql ORDER BY o.id DESC LIMIT $size OFFSET ".($page*$size));$query->execute($bind);respond(page_response(array_map('order_response',$query->fetchAll()),$page,$size,$total)); }
function users_page(): never { $where=['1=1'];$bind=[];if($r=$_GET['role']??null){$where[]='role=?';$bind[]=$r;}if($q=trim((string)($_GET['q']??''))){$where[]='(email LIKE ? OR first_name LIKE ? OR last_name LIKE ?)';$bind=array_merge($bind,["%$q%","%$q%","%$q%"]);}$sql=implode(' AND ',$where);$count=db()->prepare("SELECT COUNT(*) FROM users WHERE $sql");$count->execute($bind);$total=(int)$count->fetchColumn();$page=max(0,(int)($_GET['page']??0));$size=min(100,max(1,(int)($_GET['size']??20)));$query=db()->prepare("SELECT id,email,first_name,last_name,phone,role,enabled FROM users WHERE $sql ORDER BY id DESC LIMIT $size OFFSET ".($page*$size));$query->execute($bind);respond(page_response(array_map('user_response',$query->fetchAll()),$page,$size,$total)); }
function save_category(?int $id=null): never { $b=json_body();require_fields($b,['name']);$slug=trim((string)($b['slug']??''))?:slugify($b['name']);if($id){db()->prepare('UPDATE categories SET name=?,slug=?,parent_id=? WHERE id=?')->execute([$b['name'],$slug,$b['parentId']??null,$id]);}else{db()->prepare('INSERT INTO categories(name,slug,parent_id) VALUES(?,?,?)')->execute([$b['name'],$slug,$b['parentId']??null]);$id=(int)db()->lastInsertId();}$q=db()->prepare('SELECT * FROM categories WHERE id=?');$q->execute([$id]);respond(category_response($q->fetch()),$id?200:201); }
function save_product(?int $id=null): never { $b=json_body();require_fields($b,['name','categoryId']);$pdo=db();$pdo->beginTransaction();try{if($id){$pdo->prepare('UPDATE products SET name=?,description=?,image_url=?,category_id=? WHERE id=?')->execute([$b['name'],$b['description']??null,$b['imageUrl']??null,(int)$b['categoryId'],$id]);}else{$slug=slugify($b['name']);$base=$slug;$n=1;while(true){try{$pdo->prepare('INSERT INTO products(name,slug,description,image_url,category_id) VALUES(?,?,?,?,?)')->execute([$b['name'],$slug,$b['description']??null,$b['imageUrl']??null,(int)$b['categoryId']]);break;}catch(PDOException $e){if((int)$e->errorInfo[1]!==1062)throw $e;$slug=$base.'-'.(++$n);}}$id=(int)$pdo->lastInsertId();foreach($b['variants']??[] as $v){require_fields($v,['format','price','stock']);validate_catalog_amounts($v);$pdo->prepare('INSERT INTO product_variants(product_id,sku,format,price,stock,low_stock_threshold) VALUES(?,?,?,?,?,?)')->execute([$id,'KIC-'.strtoupper(substr(hash('sha256',uniqid('',true)),0,10)),$v['format'],(int)$v['price'],(int)$v['stock'],(int)($v['lowStockThreshold']??10)]);}}$pdo->commit();respond(product_response(product_row($id)),201);}catch(Throwable $e){$pdo->rollBack();throw $e;} }
function save_variant(int $productId,?int $id=null): never { $b=json_body();require_fields($b,['format','price','stock']);validate_catalog_amounts($b);if($id){db()->prepare('UPDATE product_variants SET format=?,price=?,stock=?,low_stock_threshold=? WHERE id=?')->execute([$b['format'],(int)$b['price'],(int)$b['stock'],(int)($b['lowStockThreshold']??10),$id]);}else{db()->prepare('INSERT INTO product_variants(product_id,sku,format,price,stock,low_stock_threshold) VALUES(?,?,?,?,?,?)')->execute([$productId,'KIC-'.strtoupper(substr(hash('sha256',uniqid('',true)),0,10)),$b['format'],(int)$b['price'],(int)$b['stock'],(int)($b['lowStockThreshold']??10)]);$id=(int)db()->lastInsertId();}$q=db()->prepare('SELECT * FROM product_variants WHERE id=?');$q->execute([$id]);respond(variant_response($q->fetch()),201); }

function handle_admin_routes(string $method,string $path,array &$params): bool
{
    $catalogWrite=in_array($method,['POST','PUT','DELETE'],true)&&(str_starts_with($path,'/products')||str_starts_with($path,'/variants')||str_starts_with($path,'/categories'));
    if(!str_starts_with($path,'/admin/')&&!in_array($path,['/users','/audit-logs'],true)&&!$catalogWrite)return false;
    $admin=current_user(true,'ADMIN');
    handle_extra_admin_routes($method,$path,$params,$admin);
    if($method==='GET'&&$path==='/admin/orders')admin_orders();
    if($method==='GET'&&route_matches('/admin/orders/{number}',$path,$params))respond(order_response(find_order($params['number'],true)));
    if($method==='PUT'&&route_matches('/admin/orders/{number}/status',$path,$params)){$b=json_body();require_fields($b,['status']);$allowed=['PENDING','PAID','SHIPPED','DELIVERED','CANCELLED'];if(!in_array($b['status'],$allowed,true))fail(422,'VALIDATION_ERROR','Statut invalide.');$o=find_order($params['number'],true);admin_change_order_status($o,$b['status']);audit_admin($admin);respond(order_response(find_order($params['number'],true)));}
    if($method==='PUT'&&route_matches('/admin/orders/{number}/tracking',$path,$params)){$b=json_body();$o=find_order($params['number'],true);db()->prepare('UPDATE orders SET tracking_note=? WHERE id=?')->execute([$b['trackingNote']??null,$o['id']]);audit_admin($admin);respond(order_response(find_order($params['number'],true)));}
    if($method==='GET'&&$path==='/users')users_page();
    if($method==='PUT'&&route_matches('/admin/users/{id}/role',$path,$params)){$b=json_body();require_fields($b,['role']);if(!in_array($b['role'],['USER','ADMIN'],true))fail(422,'VALIDATION_ERROR','Role invalide.');db()->prepare('UPDATE users SET role=? WHERE id=?')->execute([$b['role'],(int)$params['id']]);audit_admin($admin);$q=db()->prepare('SELECT id,email,first_name,last_name,phone,role,enabled FROM users WHERE id=?');$q->execute([(int)$params['id']]);respond(user_response($q->fetch()));}
    if($method==='PUT'&&route_matches('/admin/users/{id}/status',$path,$params)){$b=json_body();if((int)$params['id']===(int)$admin['id'])fail(409,'SELF_MODIFICATION','Vous ne pouvez pas desactiver votre propre compte.');db()->prepare('UPDATE users SET enabled=? WHERE id=?')->execute([!empty($b['enabled'])?1:0,(int)$params['id']]);audit_admin($admin);$q=db()->prepare('SELECT id,email,first_name,last_name,phone,role,enabled FROM users WHERE id=?');$q->execute([(int)$params['id']]);respond(user_response($q->fetch()));}
    if($method==='GET'&&$path==='/admin/stats/dashboard'){$by=[];foreach(db()->query('SELECT status,COUNT(*) count FROM orders GROUP BY status') as $r)$by[$r['status']]=(int)$r['count'];respond(['totalOrders'=>(int)db()->query('SELECT COUNT(*) FROM orders')->fetchColumn(),'ordersByStatus'=>$by,'revenue'=>(int)db()->query("SELECT COALESCE(SUM(total),0) FROM orders WHERE status IN ('PAID','SHIPPED','DELIVERED')")->fetchColumn(),'currency'=>'EUR','totalUsers'=>(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn(),'totalProducts'=>(int)db()->query('SELECT COUNT(*) FROM products WHERE active=1')->fetchColumn(),'lowStockVariants'=>(int)db()->query('SELECT COUNT(*) FROM product_variants WHERE stock<=low_stock_threshold')->fetchColumn()]);}
    if($method==='GET'&&$path==='/admin/stats/best-sellers'){$limit=min(50,max(1,(int)($_GET['limit']??5)));$q=db()->query("SELECT oi.product_name productName,SUM(oi.quantity) totalQuantity,SUM(oi.line_total) totalRevenue FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.status IN ('PAID','SHIPPED','DELIVERED') GROUP BY oi.product_name ORDER BY totalQuantity DESC LIMIT $limit");respond(array_map(fn($r)=>['productName'=>$r['productName'],'totalQuantity'=>(int)$r['totalQuantity'],'totalRevenue'=>(int)$r['totalRevenue']],$q->fetchAll()));}
    if($method==='GET'&&$path==='/audit-logs'){$page=max(0,(int)($_GET['page']??0));$size=min(100,max(1,(int)($_GET['size']??20)));$total=(int)db()->query('SELECT COUNT(*) FROM audit_logs')->fetchColumn();$q=db()->query('SELECT id,actor,method,path,status,created_at FROM audit_logs ORDER BY id DESC LIMIT '.$size.' OFFSET '.($page*$size));$rows=array_map(fn($r)=>['id'=>(int)$r['id'],'actor'=>$r['actor'],'method'=>$r['method'],'path'=>$r['path'],'status'=>(int)$r['status'],'timestamp'=>date(DATE_ATOM,strtotime($r['created_at']))],$q->fetchAll());respond(page_response($rows,$page,$size,$total));}
    if($method==='POST'&&$path==='/categories')save_category();if($method==='PUT'&&route_matches('/categories/{id}',$path,$params))save_category((int)$params['id']);
    if($method==='POST'&&$path==='/products')save_product();if($method==='PUT'&&route_matches('/products/{id}',$path,$params))save_product((int)$params['id']);
    if($method==='POST'&&route_matches('/products/{id}/variants',$path,$params))save_variant((int)$params['id']);if($method==='PUT'&&route_matches('/variants/{id}',$path,$params))save_variant(0,(int)$params['id']);
    if($method==='DELETE'&&route_matches('/variants/{id}',$path,$params)){db()->prepare('DELETE FROM product_variants WHERE id=?')->execute([(int)$params['id']]);audit_admin($admin,204);respond(null,204);}if($method==='DELETE'&&route_matches('/products/{id}',$path,$params)){db()->prepare('UPDATE products SET active=0 WHERE id=?')->execute([(int)$params['id']]);audit_admin($admin,204);respond(null,204);}if($method==='DELETE'&&route_matches('/categories/{id}',$path,$params)){try{db()->prepare('DELETE FROM categories WHERE id=?')->execute([(int)$params['id']]);}catch(PDOException){fail(409,'CATEGORY_IN_USE','Cette categorie contient des produits.');}audit_admin($admin,204);respond(null,204);}
    return true;
}
